#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#

# check to see if I used a message, then it will behave as a put 
#bash shell script check input argument

# set working directory as the scripts location during the execution of script 
# cd "$(dirname "$0")"


ACTION=`basename "$0"`

# check operation systems 
(
  if [[ "$(uname)" == "Darwin" ]] ; then 
    # Do something under Mac OS X platform    
    sysctl hw.model | awk '{ print $2 }'
    ioreg -l | awk -F\" '/board-id/ { print $4 }'
  
  elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]] ; then 
    # Do something under GNU/Linux platform
    echo "nothing"
  
  elif [[ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]] ; then 
    # Do something under Windows NT platform
     echo "nothing"
    # nothing here
  fi 
)
